export const queryKeys = {
  session: ['session', 'me'] as const,
  companies: ['companies'] as const,
  projects: ['projects'] as const,
  project: (projectId: string) => ['projects', projectId] as const,
  documents: (projectId: string) => ['projects', projectId, 'documents'] as const,
  document: (documentId: string) => ['documents', documentId] as const,
  anchors: (versionId: string) => ['document-versions', versionId, 'anchors'] as const,
  tasks: (projectId: string) => ['projects', projectId, 'tasks'] as const,
  facts: (projectId: string) => ['projects', projectId, 'facts'] as const,
  fact: (factId: string) => ['facts', factId] as const,
  factEvidence: (factId: string) => ['facts', factId, 'evidence'] as const,
  factRevisions: (factId: string) => ['facts', factId, 'revisions'] as const,
  factConflicts: (projectId: string) => ['projects', projectId, 'fact-conflicts'] as const,
  factConflict: (groupId: string) => ['fact-conflicts', groupId] as const,
  standards: ['standards'] as const,
  standardVersions: (standardId: string) => ['standards', standardId, 'versions'] as const,
  projectStandards: (projectId: string) => ['projects', projectId, 'standards'] as const,
  disclosures: (projectId: string) => ['projects', projectId, 'disclosures'] as const,
  disclosure: (projectId: string, projectDisclosureId: string) =>
    ['projects', projectId, 'disclosures', projectDisclosureId] as const,
  requirements: (projectId: string) => ['projects', projectId, 'requirements'] as const,
  missingItems: (projectId: string) => ['projects', projectId, 'missing-items'] as const,
  reports: (projectId: string) => ['projects', projectId, 'reports'] as const,
  report: (reportId: string) => ['reports', reportId] as const,
  sections: (reportId: string) => ['reports', reportId, 'sections'] as const,
  section: (sectionId: string) => ['sections', sectionId] as const,
  sectionDisclosures: (sectionId: string) => ['sections', sectionId, 'disclosures'] as const,
  sectionPlanningContext: (sectionId: string) => ['sections', sectionId, 'planning-context'] as const,
};
