ROLE_ACTIONS={
 'OWNER': {'VIEW_PROJECT','EDIT_PROJECT','MANAGE_MEMBERS','UPLOAD_DOCUMENT','VIEW_FACT','CONFIRM_FACT','EDIT_REPORT','GENERATE_REPORT','COMMENT'},
 'EDITOR': {'VIEW_PROJECT','EDIT_PROJECT','UPLOAD_DOCUMENT','VIEW_FACT','CONFIRM_FACT','EDIT_REPORT','GENERATE_REPORT','COMMENT'},
 'REVIEWER': {'VIEW_PROJECT','VIEW_FACT','COMMENT'},
 'CLIENT_MEMBER': {'VIEW_PROJECT','UPLOAD_DOCUMENT','VIEW_FACT','CONFIRM_FACT','COMMENT'},
}
def allows(role:str|None, action:str)->bool: return bool(role and action in ROLE_ACTIONS.get(role,set()))
